# Generated by Django 2.2.8 on 2020-05-04 15:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200429_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 4, 15, 53, 24, 727872, tzinfo=utc)),
        ),
    ]
